### ISSUE TITLE
Add disclaimer at the bottom of the page

### ISSUE THREAD

**Issue by benrudolph** [benrudolph/BaaR#2]

**Comment by Arnetreves** [comment]
“Impressum
BaaR UG (haftungsbeschränkt) | Gneisenaustrasse 26 | 10961 Berlin
Arne(at)baar-music.de |  +4917623866437 

Registergericht: AG Charlottenburg Berlin, HRB-Nummer: 121349 B
Vertretungsberechtigter Geschäftsführer: Arne Treves“
